export interface Tool {
  name: string;
  description: string;
  href: string;
  icon: string;
  category: string;
}

export const tools: Tool[] = [
  {
    name: "图片压缩",
    description: "在线压缩图片，支持 JPG/PNG/WebP，批量处理",
    href: "/tools/image-compress",
    icon: "🖼️",
    category: "图片工具",
  },
  {
    name: "图片格式转换",
    description: "JPG/PNG/WebP/SVG 互转，支持批量",
    href: "/tools/image-convert",
    icon: "🔄",
    category: "图片工具",
  },
  {
    name: "PDF 合并拆分",
    description: "合并多个 PDF 或拆分为单独页面",
    href: "/tools/pdf",
    icon: "📄",
    category: "PDF 工具",
  },
  {
    name: "JSON 格式化",
    description: "美化、压缩、校验 JSON 数据",
    href: "/tools/json",
    icon: "{ }",
    category: "开发工具",
  },
  {
    name: "文本处理",
    description: "去重、排序、大小写转换、字数统计",
    href: "/tools/text",
    icon: "📝",
    category: "文本工具",
  },
  {
    name: "Base64 编解码",
    description: "文本与 Base64 互转，支持图片",
    href: "/tools/base64",
    icon: "🔐",
    category: "开发工具",
  },
  {
    name: "正则测试器",
    description: "在线测试正则表达式，高亮匹配结果",
    href: "/tools/regex",
    icon: "🔍",
    category: "开发工具",
  },
  {
    name: "二维码生成",
    description: "输入文本或链接生成二维码图片",
    href: "/tools/qrcode",
    icon: "📱",
    category: "图片工具",
  },
  {
    name: "颜色工具",
    description: "取色器、颜色格式转换、对比度检查",
    href: "/tools/color",
    icon: "🎨",
    category: "设计工具",
  },
  {
    name: "时间戳转换",
    description: "时间戳与日期互转，支持多时区",
    href: "/tools/timestamp",
    icon: "⏰",
    category: "开发工具",
  },
  {
    name: "密码生成器",
    description: "生成随机安全密码，支持自定义规则",
    href: "/tools/password",
    icon: "🔑",
    category: "安全工具",
  },
  {
    name: "UUID 生成器",
    description: "生成随机 UUID v4 唯一标识符",
    href: "/tools/uuid",
    icon: "🆔",
    category: "开发工具",
  },
  {
    name: "哈希计算",
    description: "计算 SHA-1/SHA-256/SHA-512 哈希值",
    href: "/tools/hash",
    icon: "#️⃣",
    category: "安全工具",
  },
  {
    name: "URL 编解码",
    description: "URL 与编码互转",
    href: "/tools/url-encode",
    icon: "🔗",
    category: "开发工具",
  },
  {
    name: "Markdown 编辑器",
    description: "实时预览 Markdown，支持导出 HTML",
    href: "/tools/markdown",
    icon: "✍️",
    category: "文本工具",
  },
  {
    name: "文本对比",
    description: "比较两段文本的差异，高亮变更",
    href: "/tools/diff",
    icon: "📊",
    category: "文本工具",
  },
  {
    name: "JWT 解码",
    description: "解析 JSON Web Token，查看 Header 和 Payload",
    href: "/tools/jwt",
    icon: "🎟️",
    category: "安全工具",
  },
  {
    name: "Cron 解析",
    description: "解析定时任务表达式，预测下次执行",
    href: "/tools/cron",
    icon: "⏲️",
    category: "开发工具",
  },
  {
    name: "YAML/JSON 互转",
    description: "JSON 和 YAML 格式互相转换",
    href: "/tools/yaml-json",
    icon: "🔀",
    category: "开发工具",
  },
  {
    name: "HTML 实体编解码",
    description: "HTML 特殊字符转义与反转义",
    href: "/tools/html-entity",
    icon: "🌐",
    category: "开发工具",
  },
  {
    name: "单位换算",
    description: "长度、重量、温度、面积、速度等单位换算",
    href: "/tools/unit-convert",
    icon: "📏",
    category: "实用工具",
  },
  {
    name: "Lorem 生成器",
    description: "生成随机占位文本用于设计排版",
    href: "/tools/lorem",
    icon: "📄",
    category: "文本工具",
  },
  {
    name: "CSS 压缩",
    description: "CSS 美化格式化与压缩",
    href: "/tools/css-minify",
    icon: "💅",
    category: "开发工具",
  },
  {
    name: "图片调整尺寸",
    description: "按像素精确调整图片大小",
    href: "/tools/image-resize",
    icon: "📐",
    category: "图片工具",
  },
  {
    name: "列表随机排序",
    description: "打乱列表顺序、随机抽签、排序",
    href: "/tools/list-random",
    icon: "🎲",
    category: "实用工具",
  },
  {
    name: "进制转换",
    description: "HEX / 二进制 / 八进制 / 十进制 互转",
    href: "/tools/base-convert",
    icon: "🔢",
    category: "开发工具",
  },
  {
    name: "字符串分析器",
    description: "字符详情、编码分析、长度统计",
    href: "/tools/string-inspect",
    icon: "🔬",
    category: "开发工具",
  },
  {
    name: "JSON 转 TypeScript",
    description: "JSON 自动生成 TypeScript 类型定义",
    href: "/tools/json-to-ts",
    icon: "🧬",
    category: "开发工具",
  },
  {
    name: "CSS 渐变生成器",
    description: "可视化生成 CSS 渐变代码",
    href: "/tools/gradient",
    icon: "🌈",
    category: "设计工具",
  },
  {
    name: "秒表/计时器",
    description: "在线计时、倒计时",
    href: "/tools/timer",
    icon: "⏱️",
    category: "实用工具",
  },
  {
    name: "CSS 阴影生成器",
    description: "可视化生成 box-shadow 代码",
    href: "/tools/box-shadow",
    icon: "📦",
    category: "设计工具",
  },
  {
    name: "SQL 格式化",
    description: "美化/压缩 SQL 语句",
    href: "/tools/sql-format",
    icon: "🗃️",
    category: "开发工具",
  },
  {
    name: "日期计算",
    description: "日期加减天数、计算两日期差",
    href: "/tools/date-calc",
    icon: "📅",
    category: "实用工具",
  },
  {
    name: "百分比计算",
    description: "各种百分比运算",
    href: "/tools/percent",
    icon: "%",
    category: "实用工具",
  },
  {
    name: "JSON/CSV 互转",
    description: "JSON 和 CSV 格式互相转换",
    href: "/tools/json-csv",
    icon: "📋",
    category: "开发工具",
  },
  {
    name: "随机数据生成",
    description: "生成假姓名、手机号、地址等测试数据",
    href: "/tools/random-data",
    icon: "🎰",
    category: "开发工具",
  },
  {
    name: "文字转 Unicode",
    description: "文字与 Unicode/HTML实体/CSS编码 互转",
    href: "/tools/unicode",
    icon: "🔤",
    category: "开发工具",
  },
  {
    name: "Emoji 大全",
    description: "分类查找复制 Emoji",
    href: "/tools/emoji",
    icon: "😀",
    category: "实用工具",
  },
  {
    name: "简易计算器",
    description: "在线科学计算器",
    href: "/tools/calculator",
    icon: "🧮",
    category: "实用工具",
  },
  {
    name: "配色方案生成",
    description: "互补色、三色、类似色等配色方案",
    href: "/tools/color-scheme",
    icon: "🎨",
    category: "设计工具",
  },
  {
    name: "提词器",
    description: "全屏滚动文本，录视频/直播用",
    href: "/tools/teleprompter",
    icon: "📺",
    category: "实用工具",
  },
  {
    name: "手持弹幕",
    description: "大字 LED 滚动，接人/应援用",
    href: "/tools/danmu",
    icon: "📟",
    category: "实用工具",
  },
  {
    name: "简繁转换",
    description: "中文简体繁体互转",
    href: "/tools/s2t",
    icon: "🀄",
    category: "文本工具",
  },
  {
    name: "图片加水印",
    description: "给图片加文字水印",
    href: "/tools/watermark",
    icon: "💧",
    category: "图片工具",
  },
  {
    name: "图片拼接",
    description: "多张图片横/纵向拼接",
    href: "/tools/image-merge",
    icon: "🧩",
    category: "图片工具",
  },
  {
    name: "文字转语音",
    description: "浏览器朗读文字",
    href: "/tools/tts",
    icon: "🔊",
    category: "文本工具",
  },
  {
    name: "番茄钟",
    description: "25分钟专注计时",
    href: "/tools/pomodoro",
    icon: "🍅",
    category: "实用工具",
  },
  {
    name: "PDF 转图片",
    description: "PDF 页面导出为 PNG",
    href: "/tools/pdf-to-img",
    icon: "🖼️",
    category: "PDF 工具",
  },
  {
    name: "文件格式转换",
    description: "PDF/Word/图片 互转",
    href: "/tools/file-convert",
    icon: "🔄",
    category: "PDF 工具",
  },
  {
    name: "BMI 计算器",
    description: "身体质量指数计算",
    href: "/tools/bmi",
    icon: "⚖️",
    category: "实用工具",
  },
  {
    name: "电子签名",
    description: "在线手写签名导出图片",
    href: "/tools/signature",
    icon: "✍️",
    category: "实用工具",
  },
];

const allCategories = [...new Set(tools.map((t) => t.category))];
export const categories = ["实用工具", ...allCategories.filter((c) => c !== "实用工具")];
